name: Coffee-Shop-CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu kopyala
        uses: actions/checkout@v4

      - name: Saytın avtomatik yerləşdirilməsi
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages