name: Samir-Coffee-Shop-CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu kopyala
        uses: actions/checkout@v4

      - name: Layihe strukturunu yoxla
        run: |
          echo "DevOps Yoxlanisi Baslayir..."
          ls -R
          echo "Butun fayllar yerindedir. Vercel Deploy-a hazirdir!"